version: '3'

services:
  test:
    image: node:12
    command: npm run test-watch
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
    ports:
      - 4000
    environment:
      NODE_ENV: test
      VIRTUAL_HOST: api-test.localtest.me
      VIRTUAL_PORT: 4000
