version: '3'

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  site:
    image: node:12
    command: npm start
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
    ports:
      - 3000
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: site.localtest.me
      VIRTUAL_PORT: 3000
      REACT_APP_API_URL: http://api.localtest.me/api

  api:
    image: node:12
    command: npm run dev
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
    ports:
      - 3000
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: api.localtest.me
      VIRTUAL_PORT: 3000
      ENABLE_NODE_CLUSTER: 'false'
